name: CI Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Install dependencies
        run: |
          - npm ci

      - name: Lint code
        run: |
          - npm run lint

      - name: Test code
        run: |
          - npm test

      - name: Package
        run: |
          - npm run package
